[features]
seeds = false
skip-lint = false
[programs.devnet]
coll_nft = "C4K3QPmcaN6JSLmwNFvZ5ZwSQV3tyCnMbTDY4tVN94sk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/varsha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
